FROM python:3.11-slim

WORKDIR /app

# prevent Python from writing .pyc files
ENV PYTHONDONTWRITEBYTECODE 1

# ensure Python output is sent directly to the terminal without buffering
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y gcc

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Copy the environment variables file (ensure this is done after installing requirements)
COPY .dev.env /app/.dev.env

# Set PYTHONPATH environment variable
ENV PYTHONPATH=/app/legido:$PYTHONPATH

# without this line perhaps the entrypoint.sh is not copied to the container
# COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# COPY . /usr/src/app/
# Give execute permissions to the entrypoint script
RUN chmod +x /app/entrypoint.sh
# Set the entrypoint script to run
ENTRYPOINT ["/app/entrypoint.sh"]